"""
Auto-render the LangGraph workflow as Mermaid + PNG.
Used by the CI/CD workflow to keep docs/workflow.md in sync with agent.py.

Usage:
    python -m app.tools.render_graph
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running as `python -m app.tools.render_graph` or as a plain script
sys.path.insert(0, str(Path(__file__).parent.parent))

from agent import build_graph  # noqa: E402


def main():
    graph = build_graph()
    g = graph.get_graph()

    docs_dir = Path(__file__).parent.parent.parent / "docs"
    docs_dir.mkdir(exist_ok=True)

    # ── Mermaid diagram (rendered natively by GitHub Markdown) ─────
    mermaid = g.draw_mermaid()
    workflow_md = docs_dir / "workflow.md"
    workflow_md.write_text(
        "# Tender Synopsis Agent - Workflow\n\n"
        "> Auto-generated by `python -m app.tools.render_graph` on every push to `app/agent.py`.\n"
        "> Do NOT edit by hand. The Mermaid source below is re-rendered from `build_graph()`.\n\n"
        "```mermaid\n" + mermaid + "\n```\n",
        encoding="utf-8",
    )
    print(f"[render_graph] Wrote {workflow_md}")

    # ── PNG (best-effort; needs internet for mermaid.ink OR pyppeteer) ─
    try:
        png_bytes = g.draw_mermaid_png()
        png_path = docs_dir / "langgraph_diagram.png"
        png_path.write_bytes(png_bytes)
        print(f"[render_graph] Wrote {png_path}")
    except Exception as e:
        print(f"[render_graph] PNG render skipped: {e}")


if __name__ == "__main__":
    main()