name: Aggregate Static ORD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: dev
        type: choice
        options: [dev, test, pre-prod, prod]

jobs:
  aggregate:
    uses: application-foundation/ci-cd-workflow/.github/workflows/aggregate-static-ord.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
